---
- name: Create user
  hosts: vmware_hosts
  tasks:
    - name: Create group
      group:
        name: "{{ item['group'] }}"
        state: present
      loop: "{{ samba_user }}"

    - name: Create user
      user:
        name: "{{ item['username'] }}"
        group: "{{ item['group'] }}"
        password: "{{ item['password'] }}"
        shell: /bin/bash
        create_home: yes
      loop: "{{ samba_user }}"